.build:
  extends: .rules
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  variables:
    COMPONENT: "testing"
    API_IMAGE_SOURCE: "https://github.com/passbolt/passbolt_api"
    IMAGE_DESCRIPTION: "Passbolt CE Backend, a JSON API written with CakePHP"
  script:
    - |
      cat << EOF > /kaniko/.docker/config.json
      {
          "auths": {
              "https://index.docker.io/v1/": {
                  "auth": "${AUTH_STRING_DOCKER_HUB}"
              },
              "$CI_REGISTRY": {
                  "username": "${CI_REGISTRY_USER}",
                  "password": "${CI_REGISTRY_PASSWORD}"
              }
          }
      }
      EOF
    - |
      echo "********************************************"
      echo "Build details"
      echo "============================================"
      echo "Flavour ${PASSBOLT_FLAVOUR:-local}"
      echo "Commit  ${UPSTREAM_COMMIT_SHA:-latest}"
      echo "********************************************"
    - |
      /kaniko/executor --context $CI_PROJECT_DIR \
        --build-arg API_REPOSITORY="${API_IMAGE_SOURCE}" \
        --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')" \
        --build-arg IMAGE_DESCRIPTION="${IMAGE_DESCRIPTION}" \
        --build-arg PASSBOLT_COMPONENT="$COMPONENT" \
        --build-arg PASSBOLT_FLAVOUR="$PASSBOLT_FLAVOUR" \
        --build-arg SUPERCRONIC_ARCH="${SUPERCRONIC_ARCH}" \
        --build-arg SUPERCRONIC_SHA1SUM="${SUPERCRONIC_SHA1SUM}" \
        --dockerfile $CI_PROJECT_DIR/$DOCKERFILE_PATH \
        --custom-platform $PLATFORM \
        --destination $CI_REGISTRY_IMAGE:${PASSBOLT_FLAVOUR:-local}-${DOCKER_TAG}-$(date +%s) \
        --destination $CI_REGISTRY_IMAGE:${PASSBOLT_FLAVOUR:-local}-${DOCKER_TAG}-latest

.stable-build:
  extends: .build
  variables:
    COMPONENT: "stable"
    PASSBOLT_FLAVOUR: "ce"
    OPPOSITE_FLAVOUR: "pro"

.stable-build-pro:
  extends: .build
  variables:
    API_IMAGE_SOURCE: "https://bitbucket.org/passbolt_pro/passbolt_pro_api"
    COMPONENT: "stable"
    IMAGE_DESCRIPTION: "Passbolt PRO Backend, a JSON API written with CakePHP"
    PASSBOLT_FLAVOUR: "pro"
    OPPOSITE_FLAVOUR: "ce"

build-ce-stable-docker:
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root"
    SUPERCRONIC_ARCH: amd64
    SUPERCRONIC_SHA1SUM: bc072eba2ae083849d5f86c6bd1f345f6ed902d0
    PLATFORM: "linux/amd64"

build-ce-stable-rootless:
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless"
    SUPERCRONIC_ARCH: amd64
    SUPERCRONIC_SHA1SUM: bc072eba2ae083849d5f86c6bd1f345f6ed902d0
    PLATFORM: "linux/amd64"

build-pro-stable-docker:
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root"
    SUPERCRONIC_ARCH: amd64
    SUPERCRONIC_SHA1SUM: bc072eba2ae083849d5f86c6bd1f345f6ed902d0
    PLATFORM: "linux/amd64"

build-pro-stable-rootless:
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless"
    SUPERCRONIC_ARCH: amd64
    SUPERCRONIC_SHA1SUM: bc072eba2ae083849d5f86c6bd1f345f6ed902d0
    PLATFORM: "linux/amd64"

build-ce-stable-docker-arm64-v8:
  tags:
    - arm
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root-arm64-v8"
    PLATFORM: "linux/arm64/v8"
    SUPERCRONIC_ARCH: arm64
    SUPERCRONIC_SHA1SUM: 37842646e4c95b193c469afae400966565c383d3

build-ce-stable-rootless-arm64-v8:
  tags:
    - arm
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless-arm64-v8"
    PLATFORM: "linux/arm64/v8"
    SUPERCRONIC_ARCH: arm64
    SUPERCRONIC_SHA1SUM: 37842646e4c95b193c469afae400966565c383d3

build-pro-stable-docker-arm64-v8:
  tags:
    - arm
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root-arm64-v8"
    PLATFORM: "linux/arm64/v8"
    SUPERCRONIC_ARCH: arm64
    SUPERCRONIC_SHA1SUM: 37842646e4c95b193c469afae400966565c383d3

build-pro-stable-rootless-arm64-v8:
  tags:
    - arm
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless-arm64-v8"
    PLATFORM: "linux/arm64/v8"
    SUPERCRONIC_ARCH: arm64
    SUPERCRONIC_SHA1SUM: 37842646e4c95b193c469afae400966565c383d3

build-ce-stable-docker-arm-v5:
  tags:
    - arm
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root-arm-v5"
    PLATFORM: "linux/arm/v5"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 510b84b031b78ebe25b1f00c91ced3434edcd383

build-ce-stable-rootless-arm-v5:
  tags:
    - arm
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless-arm-v5"
    PLATFORM: "linux/arm/v5"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 510b84b031b78ebe25b1f00c91ced3434edcd383

build-pro-stable-docker-arm-v5:
  tags:
    - arm
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root-arm-v5"
    PLATFORM: "linux/arm/v5"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 510b84b031b78ebe25b1f00c91ced3434edcd383

build-pro-stable-rootless-arm-v5:
  tags:
    - arm
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless-arm-v5"
    PLATFORM: "linux/arm/v5"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 510b84b031b78ebe25b1f00c91ced3434edcd383

build-ce-stable-docker-arm-v7:
  tags:
    - arm
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root-arm-v7"
    PLATFORM: "linux/arm/v7"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 510b84b031b78ebe25b1f00c91ced3434edcd383

build-ce-stable-rootless-arm-v7:
  tags:
    - arm
  extends: .stable-build
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless-arm-v7"
    PLATFORM: "linux/arm/v7"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 510b84b031b78ebe25b1f00c91ced3434edcd383

build-pro-stable-docker-arm-v7:
  tags:
    - arm
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile"
    DOCKER_TAG: "root-arm-v7"
    PLATFORM: "linux/arm/v7"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 510b84b031b78ebe25b1f00c91ced3434edcd383

build-pro-stable-rootless-arm-v7:
  tags:
    - arm
  extends: .stable-build-pro
  variables:
    DOCKERFILE_PATH: "debian/Dockerfile.rootless"
    DOCKER_TAG: "rootless-arm-v7"
    PLATFORM: "linux/arm/v7"
    SUPERCRONIC_ARCH: arm
    SUPERCRONIC_SHA1SUM: 510b84b031b78ebe25b1f00c91ced3434edcd383
